/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinamaxRouteImport } from './routes/winamax'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAiFallbackRouteImport } from './routes/api/public/ai-fallback'
import { Route as ApiPublicHooksRefreshWinamaxRouteImport } from './routes/api/public/hooks/refresh-winamax'

const WinamaxRoute = WinamaxRouteImport.update({
  id: '/winamax',
  path: '/winamax',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiFallbackRoute = ApiPublicAiFallbackRouteImport.update({
  id: '/api/public/ai-fallback',
  path: '/api/public/ai-fallback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshWinamaxRoute =
  ApiPublicHooksRefreshWinamaxRouteImport.update({
    id: '/api/public/hooks/refresh-winamax',
    path: '/api/public/hooks/refresh-winamax',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/winamax': typeof WinamaxRoute
  '/api/public/ai-fallback': typeof ApiPublicAiFallbackRoute
  '/api/public/hooks/refresh-winamax': typeof ApiPublicHooksRefreshWinamaxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/winamax': typeof WinamaxRoute
  '/api/public/ai-fallback': typeof ApiPublicAiFallbackRoute
  '/api/public/hooks/refresh-winamax': typeof ApiPublicHooksRefreshWinamaxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/winamax': typeof WinamaxRoute
  '/api/public/ai-fallback': typeof ApiPublicAiFallbackRoute
  '/api/public/hooks/refresh-winamax': typeof ApiPublicHooksRefreshWinamaxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/winamax'
    | '/api/public/ai-fallback'
    | '/api/public/hooks/refresh-winamax'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/winamax'
    | '/api/public/ai-fallback'
    | '/api/public/hooks/refresh-winamax'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/winamax'
    | '/api/public/ai-fallback'
    | '/api/public/hooks/refresh-winamax'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  WinamaxRoute: typeof WinamaxRoute
  ApiPublicAiFallbackRoute: typeof ApiPublicAiFallbackRoute
  ApiPublicHooksRefreshWinamaxRoute: typeof ApiPublicHooksRefreshWinamaxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/winamax': {
      id: '/winamax'
      path: '/winamax'
      fullPath: '/winamax'
      preLoaderRoute: typeof WinamaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-fallback': {
      id: '/api/public/ai-fallback'
      path: '/api/public/ai-fallback'
      fullPath: '/api/public/ai-fallback'
      preLoaderRoute: typeof ApiPublicAiFallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-winamax': {
      id: '/api/public/hooks/refresh-winamax'
      path: '/api/public/hooks/refresh-winamax'
      fullPath: '/api/public/hooks/refresh-winamax'
      preLoaderRoute: typeof ApiPublicHooksRefreshWinamaxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  WinamaxRoute: WinamaxRoute,
  ApiPublicAiFallbackRoute: ApiPublicAiFallbackRoute,
  ApiPublicHooksRefreshWinamaxRoute: ApiPublicHooksRefreshWinamaxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
